### ISSUE TITLE
Build number dropdown within pipeline has odd formatting

### ISSUE THREAD

**Issue by wejrox** [jenkinsci/material-theme-plugin#5]
When you create a pipeline and execute a job, you can expand the job number via a dropdown icon upon hover.

By default, the options appear with their icon and text inline, which reduces clutter. 
![Correct](https://user-images.githubusercontent.com/23255412/108147198-92c2d180-7122-11eb-87cf-ef9870468cef.PNG)

With this theme, the icons and text are separated via newlines, which causes visual disparity. 
![Incorrect](https://user-images.githubusercontent.com/23255412/108147214-99514900-7122-11eb-937f-a9f59199e534.PNG)

This theme should have its CSS updated to correct the issue, since it doesn't seem like an intended modification.

The cause of the issue is the image src being set to display block, which forces the text onto the next line.

This can be rectified by changing https://github.com/jenkinsci/material-theme-plugin/blob/master/src/main/webapp/resources/less/core-theme.less#L6 to be display: inline !important;

I'm not sure why this wasn't an issue in Jenkins when using the afonsof theme directly.

**Comment by wejrox** [comment]
This can be rectified by creating a new css entry for any images within a list to set their display to inline.

Something like the following should work?
```css
a.yuimenuitemlabel > img {
  display: inline !important;
}
```

**Comment by timbrown5** [comment]
This should be resolved in master.
![dropdown-list-icon-inline-fix](https://user-images.githubusercontent.com/4447764/112141265-fe3e0a00-8bcc-11eb-8d58-1e66ac1201a9.PNG)
If you can confirm it is fixed for you, then I will spin a release.

**Comment by timbrown5** [comment]
Should be fixed in https://github.com/jenkinsci/material-theme-plugin/releases/tag/0.3.3
