### ISSUE TITLE
Add Green and Yellow

### ISSUE THREAD

**Issue by tkensiski** [jenkinsci/material-theme-plugin#53]
### What feature do you want to see added?

The inspiration for this plugin comes from afonsof/jenkins-material-theme which had a lot more colors to choose from.
We use green, yellow and red so support for more colors would be awesome!

**Comment by tkensiski** [comment]
Note: opened this for a PR? Not sure if its actually required... so feel free to do with as you see fit.

**Comment by timbrown5** [comment]
Merged. I am hoping that the CD pipeline will release it (but can do it manually if not).
