### ISSUE TITLE
Broken icons since Jenkins release 2.289.1

### ISSUE THREAD

**Issue by livelace** [jenkinsci/material-theme-plugin#7]
### Versions

jenkins: 2.289.1
material plugin: 0.3.3 
firefox: 88.0
chrome: 91.0.4472.77

### Description

Broken icons (not animated) since Jenkins [release 2.289.1](https://www.jenkins.io/changelog-stable/) ([pull 5065](https://github.com/jenkinsci/jenkins/pull/5065), [pull 5392](https://github.com/jenkinsci/jenkins/pull/5392)) . See pics.

![build_history](https://user-images.githubusercontent.com/2379419/121195203-12161580-c878-11eb-8cb3-711c271e9d62.png)
![projects](https://user-images.githubusercontent.com/2379419/121195218-16423300-c878-11eb-835b-9dccd0042ad5.png)
![project](https://user-images.githubusercontent.com/2379419/121195230-18a48d00-c878-11eb-8138-583362c5034e.png)

**Comment by timbrown5** [comment]
I think the best way to fix this is to create a new version that stops adding custom icons for those which have been updated.

I think that will mean a new minor version (0.4), and backporting important fixes to (0.3.x).

This is likely going to be an ongoing battle with the UI changes that are planned.

**Comment by timbrown5** [comment]
I have pushed a new version to master, are you able to double-check that it works for you?

**Comment by livelace** [comment]
Yep, it works. Thanks.  

![blue](https://user-images.githubusercontent.com/2379419/122595646-72276b80-d071-11eb-80a3-73ca622669dc.png)
![blue1](https://user-images.githubusercontent.com/2379419/122595648-72c00200-d071-11eb-8af2-163113bb7866.png)

**Comment by NazarovNikita** [comment]
waiting for new release with fix, thx u

**Comment by timbrown5** [comment]
Sorry, Jenkins-ci has changed the recommended release process and I got a bit stuck when I tried before.
Falling back to the older process seems to have worked.

**Comment by timbrown5** [comment]
Last nights release uploaded to snapshots, so it's not available. I've been fighting on this morning and 0.4.1 is in the releases section:
https://repo.jenkins-ci.org/releases/io/jenkins/plugins/material-theme/0.4.1/
It should hopefully be available in the next few hours (although I've seen a number of intermittent issues with the https://repo.jenkins-ci.org/public/ this week so we shall have to wait and see).

Here is an example of the errors we've been seeing - unrelated to this bug, just mentioning in case you see something similar when fetching the update. 
> 10:56:02  [ERROR] Failed to execute goal on project material-theme: Could not resolve dependencies for project io.jenkins.plugins:material-theme:hpi:0.4.2-SNAPSHOT: Could not transfer artifact org.jenkins-ci.main:jenkins-core:jar:2.289.1 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): GET request of: org/jenkins-ci/main/jenkins-core/2.289.1/jenkins-core-2.289.1.jar from repo.jenkins-ci.org failed: Premature end of Content-Length delimited message body (expected: 11,146,641; received: 382,707) -> [Help 1]

Ref: https://ci.jenkins.io/job/Plugins/job/material-theme-plugin/job/master/31/console

**Comment by timbrown5** [comment]
There is an outage on update center
https://groups.google.com/g/jenkinsci-dev/c/vZWsHBCYOyM
I hope when this is resolved the 0.4.1 release of plugin will be available.

**Comment by timbrown5** [comment]
Seems like the release is now live.
![Screenshot 2021-07-12 at 10 44 46](https://user-images.githubusercontent.com/4447764/125266900-32654400-e2fe-11eb-908f-3186b8779354.png)
Note: this is marked as not available as the Jenkins instance this screenshot is from is using `2.277.4` and this needs `>=2.289.1`.

**Comment by NazarovNikita** [comment]
![image](https://user-images.githubusercontent.com/722447/125268313-40bc5b80-e310-11eb-8f8d-4d5255bdc421.png)
****
everything looks and works great.
Thank you so much

`jenkins 2.289.2`
