### ISSUE TITLE
Google font imports blocking UI on air gapped environments

### ISSUE THREAD

**Issue by bukovjanmic** [jenkinsci/material-theme-plugin#9]
### Feature Request

Would it be possible to get rid of font import from Google:

@import url(https://fonts.googleapis.com/css?family=Roboto:400,700,500,300);
@import url(https://fonts.googleapis.com/css?family=Roboto+Mono:400,700,500,300);

The problem is, for browsers on air-gapped environments without proxy, fonts fail to import when viewing Jenkins pages and intermittently break/slow down Jenkins UI.

It would be great if they could be included in the theme and served by Jenkins.

Thanks,

Michal

**Comment by timbrown5** [comment]
This is tricky because the URLs in the imports use the user-agent header to generate dynamic CSS files for each browser. I will have to have a look if there is a widely supported format that can be used (not sure if woff, woff2 or tff would be best)

**Comment by bukovjanmic** [comment]
Perhaps use the self-hosted Google fonts variant?

https://blog.logrocket.com/self-hosted-fonts-vs-google-fonts-api/

**Comment by zbjdonald** [comment]
Hi, any updates? China ban google, So...

**Comment by timbrown5** [comment]
I had a look earlier in the week and the suggested site (from the blogpost) was down (it was last week when I tried also).

As it's back up now I will have a look.

**Comment by timbrown5** [comment]
Would you be able to check that the PR resolves your issue?

I have done some local testing and it works for me, but I'm not in an air-gapped environment.

**Comment by timbrown5** [comment]
Sorry, this issue was closed too early (by the PR).

This should be resolved in 0.5.1-rc92.a_564b_ca_9f511 - which has just been pushed. Please allow up to a day for the plugin site to update (it should only be a few hours).

**Comment by offa** [comment]
I have tested the _master_ branch on an instance without internet connection and thus affected by this issue: Fonts and long loading times are gone :+1:.
